name: Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install Firebase CLI globally
        run: npm install -g firebase-tools

      - name: Authenticate and Deploy with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Define token a env variable
        run: firebase deploy --only hosting --project igrejaviverbemibv --token $FIREBASE_TOKEN
